### ISSUE TITLE
Wrong IP used for Musicpal discovery

### ISSUE THREAD

**Issue by cweiske** [Nutomic/controldlna#16]
`controldlna` tries to discover the Freecom MusicPal internet radio at IP 127.0.0.1:

```
04-23 13:20:27.308 25936 25973 W System.err: java.lang.IllegalArgumentException: Action can not be null
04-23 13:20:27.308 25936 25973 W System.err: 	at org.teleal.cling.model.action.ActionInvocation.<init>(ActionInvocation.java:55)
04-23 13:20:27.309 25936 25973 W System.err: 	at org.teleal.cling.model.action.ActionInvocation.<init>(ActionInvocation.java:46)
04-23 13:20:27.309 25936 25973 W System.err: 	at org.teleal.cling.support.renderingcontrol.callback.GetVolume.<init>(GetVolume.java:43)
04-23 13:20:27.309 25936 25973 W System.err: 	at org.teleal.cling.support.renderingcontrol.callback.GetVolume.<init>(GetVolume.java:39)
04-23 13:20:27.309 25936 25973 W System.err: 	at com.github.nutomic.controldlna.upnp.RemotePlayService$3.<init>(RemotePlayService.java:228)
04-23 13:20:27.309 25936 25973 W System.err: 	at com.github.nutomic.controldlna.upnp.RemotePlayService.deviceAdded(RemotePlayService.java:228)
04-23 13:20:27.309 25936 25973 W System.err: 	at com.github.nutomic.controldlna.upnp.RemotePlayService.remoteDeviceAdded(RemotePlayService.java:315)
04-23 13:20:27.309 25936 25973 W System.err: 	at org.teleal.cling.registry.RemoteItems$1.run(RemoteItems.java:110)
04-23 13:20:27.309 25936 25973 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
04-23 13:20:27.309 25936 25973 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
04-23 13:20:27.309 25936 25973 W System.err: 	at java.lang.Thread.run(Thread.java:818)
04-23 13:20:27.319 25936 25970 W trieveRemoteDescriptors: Device descriptor retrieval failed, no response: http://127.0.0.1:9000/TMRDeviceDescription.xml
04-23 13:20:27.325 25936 25970 W trieveRemoteDescriptors: Device descriptor retrieval failed, no response: http://127.0.0.1:9000/TMRDeviceDescription.xml
04-23 13:20:27.328 25936 25974 W trieveRemoteDescriptors: Device descriptor retrieval failed, no response: http://127.0.0.1:9000/TMRDeviceDescription.xml
```

I don't know if the error before has to do with the 127.0.0.1 problem.

The MusicPal is shown in the "Route" tab nontheless.

I can discover the device without problems on my linux pc:
```
$ gssdp-discover --timeout 3 --interface wlan0
resource available
  USN:      uuid:54776f6e-6b79-4d65-641e-0001db085e2f
  Location: http://192.168.3.43:9000/TMRDeviceDescription.xml
resource available
  USN:      uuid:54776f6e-6b79-4d65-641e-0001db085e2f::upnp:rootdevice
  Location: http://192.168.3.43:9000/TMRDeviceDescription.xml
resource available
  USN:      uuid:54776f6e-6b79-4d65-641e-0001db085e2f::urn:schemas-upnp-org:device:MediaRenderer:1
  Location: http://192.168.3.43:9000/TMRDeviceDescription.xml
```

Fetching the descriptor also works:
```
$ curl -s http://192.168.3.43:9000/TMRDeviceDescription.xml|xmllint --format -
<?xml version="1.0" encoding="utf-8"?>
<root xmlns="urn:schemas-upnp-org:device-1-0" xmlns:dlna="urn:schemas-dlna-org:device-1-0" xmlns:ms="urn:microsoft-com:wmc-1-0">
  <specVersion>
    <major>1</major>
    <minor>0</minor>
  </specVersion>
  <device ms:X_MS_SupportsWMDRM="true">
    <deviceType>urn:schemas-upnp-org:device:MediaRenderer:1</deviceType>
    <dlna:X_DLNADOC>DMR-1.50</dlna:X_DLNADOC>
    <dlna:X_DLNACAP/>
    <UDN>uuid:54776f6e-6b79-4d65-641e-0001db085e2f</UDN>
    <friendlyName>MusicPal</friendlyName>
    <manufacturer>Freecom</manufacturer>
    <manufacturerURL>http://www.freecom.com</manufacturerURL>
    <modelName>Freecom MusicPal</modelName>
    <modelNumber>1.67</modelNumber>
    <modelURL>http://www.musicpal.info</modelURL>
    <modelDescription>Freecom MusicPal</modelDescription>
    <serialNumber>00:01:db:08:5e:2e</serialNumber>
    <UPC/>
    <presentationURL>http://192.168.3.43:80/</presentationURL>
    <serviceList>
      <service>
        <serviceType>urn:schemas-upnp-org:service:ConnectionManager:1</serviceType>
        <serviceId>urn:upnp-org:serviceId:urn:schemas-upnp-org:service:ConnectionManager</serviceId>
        <SCPDURL>/ConnectionManager.xml</SCPDURL>
        <eventSubURL>/ConnectionManager/Event</eventSubURL>
        <controlURL>/ConnectionManager/Control</controlURL>
      </service>
      <service>
        <serviceType>urn:schemas-upnp-org:service:AVTransport:1</serviceType>
        <serviceId>urn:upnp-org:serviceId:AVTransport</serviceId>
        <SCPDURL>/AVTransport.xml</SCPDURL>
        <eventSubURL>/AVTransport/Event</eventSubURL>
        <controlURL>/AVTransport/Control</controlURL>
      </service>
      <service>
        <serviceType>urn:schemas-upnp-org:service:RenderingControl:1</serviceType>
        <serviceId>urn:upnp-org:serviceId:urn:schemas-upnp-org:service:RenderingControl</serviceId>
        <SCPDURL>/RenderingControl.xml</SCPDURL>
        <eventSubURL>/RenderingControl/Event</eventSubURL>
        <controlURL>/RenderingControl/Control</controlURL>
      </service>
    </serviceList>
  </device>
</root>
```

When music is already playing, I can pause and resume it on the MusicPal via ControlDLNA.

**Comment by cweiske** [comment]
Oh. That seems to be a bug in the MusicPal: After fetching the XML once, running discovery again yields 127.0.0.1 as IP:

```
$ gssdp-discover --timeout 3 --interface wlan0
resource available
  USN:      uuid:54776f6e-6b79-4d65-641e-0001db085e2f
  Location: http://127.0.0.1:9000/TMRDeviceDescription.xml
resource available
  USN:      uuid:54776f6e-6b79-4d65-641e-0001db085e2f::upnp:rootdevice
  Location: http://127.0.0.1:9000/TMRDeviceDescription.xml
resource available
  USN:      uuid:54776f6e-6b79-4d65-641e-0001db085e2f::urn:schemas-upnp-org:device:MediaRenderer:1
  Location: http://127.0.0.1:9000/TMRDeviceDescription.xml
resource available
  USN:      uuid:54776f6e-6b79-4d65-641e-0001db085e2f::urn:schemas-upnp-org:service:ConnectionManager:1
  Location: http://127.0.0.1:9000/TMRDeviceDescription.xml
resource available
  USN:      uuid:54776f6e-6b79-4d65-641e-0001db085e2f::urn:schemas-upnp-org:service:AVTransport:1
  Location: http://127.0.0.1:9000/TMRDeviceDescription.xml
resource available
  USN:      uuid:54776f6e-6b79-4d65-641e-0001db085e2f::urn:schemas-upnp-org:device:RenderingControl:1
  Location: http://127.0.0.1:9000/TMRDeviceDescription.xml
```
